### ISSUE TITLE
IE11 error

### ISSUE THREAD

**Issue by vbraun** [connorwyatt/Fluency-Injection#4]
es6 is too much for IE11's little brain, and it errors out at template strings. For real world usage it would probably be better to use the es5 target in tsconfig.json...

**Comment by connorwyatt** [comment]
Hi @vbraun, the target for this library is Node.js, not the browser, hence the lack of support. I'm more than happy for you to create a PR for targeting ES5, however it will need testing.

**Comment by connorwyatt** [comment]
Closing as it has gone stale.
